# Generated by Django 5.0.5 on 2024-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='buildingaddress',
            options={'verbose_name_plural': 'Building Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
