# Generated by Django 5.0.5 on 2024-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_amenity_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinginfo',
            options={'verbose_name_plural': 'Building Information'},
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
