# Generated by Django 5.0.5 on 2024-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_buildinginfo_options_buildingimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='categories',
            field=models.ManyToManyField(to='properties.category'),
        ),
    ]
